using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using HarmonyLib;
using UnityEngine;
using UnityEngine.UI;

internal sealed partial class AutomationModule
{
    private readonly List<AutomationProfile> _automationProfiles = new List<AutomationProfile>();
    private readonly HashSet<string> _automationKnownScriptFiles = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
    private int _automationProfileIndex;
    private KeyCode _automationRunKey = KeyCode.F7;
    private KeyCode _automationStopKey = KeyCode.F8;
    private bool _automationIgnoreWeightDuringExecution = true;
    private bool _automationNeedsDetectionDuringExecution = true;
    private bool _automationRunning;
    private bool _automationFeatureOverrideActive;
    private bool _automationOriginalInfinitePlayerSight;
    private bool _automationOriginalHostileThreatMarker;
    private bool _automationOriginalIgnoreWeight;
    private bool _automationIgnoreWeightOverrideApplied;
    private int _automationActionIndex = -1;
    private AutomationActionConfig? _automationCurrentAction;
    private AIAct? _automationActionAi;
    private Thing? _automationTargetThing;
    private Chara? _automationTargetChara;
    private Point? _automationTargetPoint;
    private readonly HashSet<long> _automationSkippedMinePoints = new HashSet<long>();
    private readonly HashSet<long> _automationSkippedChopPoints = new HashSet<long>();
    private readonly HashSet<long> _automationSkippedHarvestPoints = new HashSet<long>();
    private readonly HashSet<long> _automationSkippedFertilizePoints = new HashSet<long>();
    private readonly HashSet<int> _automationSkippedContainerUids = new HashSet<int>();
    private readonly HashSet<int> _automationSkippedInteractUids = new HashSet<int>();
    private readonly HashSet<int> _automationInteractedThingUids = new HashSet<int>();
    private readonly HashSet<int> _automationSkippedEnemyUids = new HashSet<int>();
    private readonly HashSet<int> _automationSkippedPickupUids = new HashSet<int>();
    private readonly HashSet<int> _automationDiscardedPickupUids = new HashSet<int>();
    private readonly HashSet<int> _automationProducedPickupUids = new HashSet<int>();
    private Map? _automationProducedPickupMap;
    private readonly Dictionary<int, int> _automationEnemyFailureCounts = new Dictionary<int, int>();
    private Point? _automationPickupOrigin;
    private bool _automationKillApproaching;
    private bool _automationInteractionPerformedForTarget;
    private bool _automationKillWaitingForEmptyRecheck;
    private int _automationKillEmptyRecheckCount;
    private float _automationKillNextEmptyRecheckAt;
    private readonly List<Chara> _automationRetaliationQueue = new List<Chara>();
    private bool _automationRetaliating;
    private Chara? _automationRetaliationTarget;
    private AutomationActionConfig? _automationRetaliationResumeAction;
    private float _automationRetaliationResumeDelay;
    private int _automationRetaliationFailureCount;
    private bool _automationNeedsMaintenance;
    private bool _automationNeedsInitialEatCompleted;
    private bool _automationNeedsSleepStarted;
    private bool _automationNeedsSleepCompleted;
    private float _automationNeedsResumeDelay;
    private int _automationNeedsLastFoodUid;
    private int _automationNeedsHungerBeforeEat;
    private readonly HashSet<int> _automationNeedsSkippedFoodUids = new HashSet<int>();
    private int _automationNeedsSleepMoveAttempts;
    private readonly HashSet<long> _automationNeedsSleepVisitedPoints = new HashSet<long>();
    private float _automationNeedsPostSleepEatAt;
    private bool _automationNeedsResumeSweep;
    private bool _automationSweepVerificationPass;
    private int _automationSweepCompletedCount;
    private int _automationStartZoneUid;
    private bool _automationZoneMoveRequested;
    private bool _automationGameLoadRequested;
    private float _automationActionStartedAt;
    private float _automationNextActionAt;
    private string _automationLog = "";
    private Text? _automationStatusText;
}
