using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Net.Http;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.CompilerServices;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Threading;
using System.Threading.Tasks;
using BepInEx;
using BepInEx.Configuration;
using BepInEx.Logging;
using BepInEx.Unity.Bootstrap;
using HarmonyLib;
using UnityEngine;

public sealed partial class ElinModifierPlugin
{
    private bool _unlockFrameRate;
    private bool _invincibleMode;
    private bool _invincibleModeIncludeParty;
    private bool _ignoreBuffEffects;
    private bool _ignoreBuffEffectsDebuff = true;
    private bool _ignoreBuffEffectsBuff;
    private bool _ignoreBuffEffectsIncludeParty;
    private readonly List<Chara> _ignoreBuffEffectsTrackedPartyMembers = new List<Chara>();
    private bool _frameRateLimitSaved;
    private int _originalVSyncCount;
    private int _originalTargetFrameRate;
    private bool _hostileThreatMarker;
    private bool _hostileThreatBehaviorPrediction = true;
    private bool _hostileThreatPredecisionLock;
    private bool _showNpcMoreInfo;
    private bool _showItemMoreInfo;
    private bool _showBuffSpecificValues;
    private int _showBuffSpecificValuesIconFontSizeOffset;
    private int _showBuffSpecificValuesTextFontSizeOffset;
    private bool _showItemPanelEnchantLevels;
    private bool _showItemPanelItemValue;
    private bool _showMainAbilityExperience;
    private bool _showMainAbilityExperienceInSkillTracker = true;
    private bool _equipmentComparison;
    private static readonly List<GameObject> _equipmentComparisonTooltips = new();
    private bool _workbenchIngredientReadingOptimization;
    [ThreadStatic] private static int _foodPotentialMultiplierDepth;
    [ThreadStatic] private static int _skillExperienceMultiplierDepth;
    private bool _unlimitedHomeResidentCap;
    private bool _unlimitedPartyMemberCap;
    private bool _unlimitedOfferingFaithPoints;
    private bool _ignoreGodArtifactFaithRequirement;
    private bool _shrineEffectSelection;
    private bool _infiniteChargeAndAmmo;
    private bool _rodStacking;
    private bool _stealHandNoTargetLimit;
    private bool _stealHandUndetectable;
    private Thing? _rodStackingTarget;
    private Thing? _rodStackingSource;
    private int _rodStackingCandidatePage;
}
