using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Net.Http;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.CompilerServices;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Threading;
using System.Threading.Tasks;
using BepInEx;
using BepInEx.Configuration;
using BepInEx.Logging;
using BepInEx.Unity.Bootstrap;
using HarmonyLib;
using UnityEngine;

public sealed partial class ElinModifierPlugin
{
    internal bool _showItemMoreInfoBasicInfo = true;
    internal bool _showItemMoreInfoGatheringThreshold = true;
    internal bool _showItemMoreInfoWeaponStats = true;
    internal bool _showItemMoreInfoEnchantments = true;
    internal bool _showItemMoreInfoPlantStats = true;
    internal bool _showItemMoreInfoPlantStatsExtended = true;
    internal int _showItemMoreInfoFontSizeOffset;
    private string _itemMoreInfoBasicInfoColor = DefaultItemMoreInfoBasicInfoColor;
    private string _itemMoreInfoGatheringToolColor = DefaultItemMoreInfoGatheringToolColor;
    private string _itemMoreInfoGatheringThresholdColor = DefaultItemMoreInfoGatheringThresholdColor;
    private string _itemMoreInfoWeaponStatsColor = DefaultItemMoreInfoWeaponStatsColor;
    private string _itemMoreInfoEnchantColor = DefaultItemMoreInfoEnchantColor;
    private string _itemMoreInfoPlantStatsColor = DefaultItemMoreInfoPlantStatsColor;
    private string _itemMoreInfoRarityCrudeColor = DefaultItemMoreInfoRarityCrudeColor;
    private string _itemMoreInfoRarityNormalColor = DefaultItemMoreInfoRarityNormalColor;
    private string _itemMoreInfoRaritySuperiorColor = DefaultItemMoreInfoRaritySuperiorColor;
    private string _itemMoreInfoRarityLegendaryColor = DefaultItemMoreInfoRarityLegendaryColor;
    private string _itemMoreInfoRarityMythicalColor = DefaultItemMoreInfoRarityMythicalColor;
    private string _itemMoreInfoRarityArtifactColor = DefaultItemMoreInfoRarityArtifactColor;
    private string _itemMoreInfoBasicInfoColorText = DefaultItemMoreInfoBasicInfoColor;
    private string _itemMoreInfoGatheringToolColorText = DefaultItemMoreInfoGatheringToolColor;
    private string _itemMoreInfoGatheringThresholdColorText = DefaultItemMoreInfoGatheringThresholdColor;
    private string _itemMoreInfoWeaponStatsColorText = DefaultItemMoreInfoWeaponStatsColor;
    private string _itemMoreInfoEnchantColorText = DefaultItemMoreInfoEnchantColor;
    private string _itemMoreInfoPlantStatsColorText = DefaultItemMoreInfoPlantStatsColor;
    private string _itemMoreInfoRarityCrudeColorText = DefaultItemMoreInfoRarityCrudeColor;
    private string _itemMoreInfoRarityNormalColorText = DefaultItemMoreInfoRarityNormalColor;
    private string _itemMoreInfoRaritySuperiorColorText = DefaultItemMoreInfoRaritySuperiorColor;
    private string _itemMoreInfoRarityLegendaryColorText = DefaultItemMoreInfoRarityLegendaryColor;
    private string _itemMoreInfoRarityMythicalColorText = DefaultItemMoreInfoRarityMythicalColor;
    private string _itemMoreInfoRarityArtifactColorText = DefaultItemMoreInfoRarityArtifactColor;
}
