using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Net.Http;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.CompilerServices;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using BepInEx;
using BepInEx.Configuration;
using BepInEx.Logging;
using BepInEx.Unity.Bootstrap;
using HarmonyLib;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using UnityEngine;

public sealed partial class ElinModifierPlugin
{
    internal bool _showNpcMoreInfoLevel = true;
    internal bool _showNpcMoreInfoIdentity = true;
    internal bool _showNpcMoreInfoRelationFaith = true;
    internal bool _showNpcMoreInfoVitals = true;
    internal bool _showNpcMoreInfoAttributes = true;
    internal bool _showNpcMoreInfoBuffs = true;
    internal bool _showNpcMoreInfoResists = true;
    internal bool _showNpcMoreInfoSkills = true;
    internal bool _showNpcMoreInfoAbilities = true;
    internal bool _showNpcMoreInfoFeats = true;
    internal bool _showNpcMoreInfoCombatSimulation = true;
    private const string DefaultNpcMoreInfoOrder = "level,identity,relation,vitals,attributes,buffs,resists,skills,abilities,feats,combat";
    internal static readonly string[] NpcMoreInfoOrderKeys = DefaultNpcMoreInfoOrder.Split(',');
    private string _showNpcMoreInfoOrder = DefaultNpcMoreInfoOrder;
    private int _showNpcMoreInfoRelationPerLine = 3;
    private int _showNpcMoreInfoVitalsPerLine = 4;
    private int _showNpcMoreInfoAttributesPerLine = 4;
    private int _showNpcMoreInfoBuffsPerLine = 5;
    private int _showNpcMoreInfoResistsPerLine = 5;
    private int _showNpcMoreInfoSkillsPerLine = 5;
    private int _showNpcMoreInfoAbilitiesPerLine = 5;
    private int _showNpcMoreInfoFeatsPerLine = 5;
    internal int _showNpcMoreInfoFontSizeOffset;
    private int _showNpcMoreInfoLevelExtraFontSize;
    private int _showNpcMoreInfoIdentityExtraFontSize;
    private int _showNpcMoreInfoRelationExtraFontSize;
    private int _showNpcMoreInfoVitalsExtraFontSize = 4;
    private int _showNpcMoreInfoAttributesExtraFontSize;
    private int _showNpcMoreInfoBuffsExtraFontSize;
    private int _showNpcMoreInfoResistsExtraFontSize;
    private int _showNpcMoreInfoSkillsExtraFontSize;
    private int _showNpcMoreInfoAbilitiesExtraFontSize;
    private int _showNpcMoreInfoFeatsExtraFontSize;
    private int _showNpcMoreInfoCombatExtraFontSize;
    private string _npcMoreInfoLevelColor = DefaultNpcMoreInfoLevelColor;
    private string _npcMoreInfoIdentityColor = DefaultNpcMoreInfoIdentityColor;
    private string _npcMoreInfoRelationColor = DefaultNpcMoreInfoRelationColor;
    private string _npcMoreInfoHpColor = DefaultNpcMoreInfoHpColor;
    private string _npcMoreInfoMpColor = DefaultNpcMoreInfoMpColor;
    private string _npcMoreInfoSpColor = DefaultNpcMoreInfoSpColor;
    private string _npcMoreInfoExpColor = DefaultNpcMoreInfoExpColor;
    private string _npcMoreInfoSpeedColor = DefaultNpcMoreInfoSpeedColor;
    private string _npcMoreInfoDvColor = DefaultNpcMoreInfoDvColor;
    private string _npcMoreInfoPvColor = DefaultNpcMoreInfoPvColor;
    private string _npcMoreInfoSkillColor = DefaultNpcMoreInfoSkillColor;
    private string _npcMoreInfoAbilityColor = DefaultNpcMoreInfoAbilityColor;
    private string _npcMoreInfoFeatColor = DefaultNpcMoreInfoFeatColor;
    private string _npcMoreInfoCombatColor = DefaultNpcMoreInfoCombatColor;
    private string _npcMoreInfoResistColor = DefaultNpcMoreInfoResistColor;
    private string _npcMoreInfoAttributeColor = DefaultNpcMoreInfoAttributeColor;
    private string _npcMoreInfoBuffColor = DefaultNpcMoreInfoBuffColor;
    private string _npcMoreInfoLevelColorText = DefaultNpcMoreInfoLevelColor;
    private string _npcMoreInfoIdentityColorText = DefaultNpcMoreInfoIdentityColor;
    private string _npcMoreInfoRelationColorText = DefaultNpcMoreInfoRelationColor;
    private string _npcMoreInfoHpColorText = DefaultNpcMoreInfoHpColor;
    private string _npcMoreInfoMpColorText = DefaultNpcMoreInfoMpColor;
    private string _npcMoreInfoSpColorText = DefaultNpcMoreInfoSpColor;
    private string _npcMoreInfoExpColorText = DefaultNpcMoreInfoExpColor;
    private string _npcMoreInfoSpeedColorText = DefaultNpcMoreInfoSpeedColor;
    private string _npcMoreInfoDvColorText = DefaultNpcMoreInfoDvColor;
    private string _npcMoreInfoPvColorText = DefaultNpcMoreInfoPvColor;
    private string _npcMoreInfoSkillColorText = DefaultNpcMoreInfoSkillColor;
    private string _npcMoreInfoAbilityColorText = DefaultNpcMoreInfoAbilityColor;
    private string _npcMoreInfoFeatColorText = DefaultNpcMoreInfoFeatColor;
    private string _npcMoreInfoCombatColorText = DefaultNpcMoreInfoCombatColor;
    private string _npcMoreInfoResistColorText = DefaultNpcMoreInfoResistColor;
    private string _npcMoreInfoAttributeColorText = DefaultNpcMoreInfoAttributeColor;
    private string _npcMoreInfoBuffColorText = DefaultNpcMoreInfoBuffColor;
}
