using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Net.Http;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.CompilerServices;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Threading;
using System.Threading.Tasks;
using BepInEx;
using BepInEx.Configuration;
using BepInEx.Logging;
using BepInEx.Unity.Bootstrap;
using HarmonyLib;
using UnityEngine;

public sealed partial class ElinModifierPlugin
{
    internal Map? _npcMoreInfoHoverCacheMap;
    internal Chara? _npcMoreInfoHoverCacheTarget;
    internal int _npcMoreInfoHoverCacheUid = -1;
    internal int _npcMoreInfoHoverCacheMask = -1;
    internal string _npcMoreInfoHoverCacheLanguage = "";
    internal int _npcMoreInfoHoverCacheFrame = -1;
    internal float _npcMoreInfoHoverCacheTime = -9999f;
    internal string _npcMoreInfoHoverCacheValue = "";
    internal Map? _npcMoreInfoSlowCacheMap;
    internal Chara? _npcMoreInfoSlowCacheTarget;
    internal int _npcMoreInfoSlowCacheUid = -1;
    internal int _npcMoreInfoSlowCacheMask = -1;
    internal string _npcMoreInfoSlowCacheLanguage = "";
    internal float _npcMoreInfoSlowCacheTime = -9999f;
    internal string _npcMoreInfoSlowIdentityCore = "";
    internal string _npcMoreInfoSlowAttributes = "";
    internal string _npcMoreInfoSlowResists = "";
    internal string _npcMoreInfoSlowSkills = "";
    internal string _npcMoreInfoSlowAbilities = "";
    internal string _npcMoreInfoSlowFeats = "";
    internal Map? _npcMoreInfoCombatCacheMap;
    internal Chara? _npcMoreInfoCombatCachePc;
    internal Chara? _npcMoreInfoCombatCacheNpc;
    internal int _npcMoreInfoCombatCachePcUid = -1;
    internal int _npcMoreInfoCombatCacheNpcUid = -1;
    internal ulong _npcMoreInfoCombatCacheFingerprint;
    internal ulong _npcMoreInfoCombatCacheDynamicFingerprint;
    internal bool _npcMoreInfoCombatCacheEstimatesValid;
    internal NpcCombatEstimate _npcMoreInfoCombatCacheKillEstimate;
    internal NpcCombatEstimate _npcMoreInfoCombatCacheDeathEstimate;
    internal float _npcMoreInfoCombatCacheCheckTime = -9999f;
    internal float _npcMoreInfoCombatCacheFullTime = -9999f;
    internal string _npcMoreInfoCombatCacheValue = "";
    internal object? _npcMoreInfoResistDefinitionSource;
    internal string _npcMoreInfoResistDefinitionLanguage = "";
    internal List<NpcMoreInfoResistDefinition>? _npcMoreInfoResistDefinitions;
}
