using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Net.Http;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.CompilerServices;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using BepInEx;
using BepInEx.Configuration;
using BepInEx.Logging;
using BepInEx.Unity.Bootstrap;
using HarmonyLib;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using UnityEngine;

public sealed partial class ElinModifierPlugin
{
    internal bool _debugAuthorized;
    private bool _debugVisible;
    private string _pluginManagerLog = "";
    private readonly List<AiPluginCacheEntry> _aiPluginCacheEntries = new List<AiPluginCacheEntry>();
    private readonly Dictionary<string, AiPluginCacheEntry> _aiPluginCacheBySignature = new Dictionary<string, AiPluginCacheEntry>(StringComparer.Ordinal);
    private string _aiPluginCacheLog = "";
    internal string _debugExceptionTrace = "No Error/Fatal log captured.";
    private string _debugStabilityTestResult = "Not run.";
    internal int _debugExceptionTraceFrame = -1;
    internal string _debugLastExceptionTraceKey = "";
    internal int _debugLastExceptionTraceFrame = -9999;
    internal readonly List<DebugExceptionTraceRecord> _debugExceptionTraceRecords = new List<DebugExceptionTraceRecord>();
    internal int _debugExceptionTraceRecordIndex = -1;
    internal readonly List<DebugSubmoduleTraceEvent> _debugSubmoduleTraceEvents = new List<DebugSubmoduleTraceEvent>();
    private bool _debugUnityLogCaptureInstalled;
    private DebugErrorLogListener _debugBepInExErrorLogListener;
    private string _debugFilter = "";
    private string _debugConfigFileFilter = "";
    private string _debugGameModuleFilter = "";
    private string _debugLog = "";
    private readonly Dictionary<string, bool> _debugExpanded = new Dictionary<string, bool>(StringComparer.Ordinal);
    private readonly Dictionary<string, string> _debugInputs = new Dictionary<string, string>(StringComparer.Ordinal);
    private readonly Dictionary<string, bool> _debugLocks = new Dictionary<string, bool>(StringComparer.Ordinal);
    private readonly Dictionary<string, DebugBinding> _debugBindings = new Dictionary<string, DebugBinding>(StringComparer.Ordinal);
    private readonly Dictionary<string, int> _debugTypePages = new Dictionary<string, int>(StringComparer.Ordinal);
    private readonly Dictionary<string, int> _debugMemberPages = new Dictionary<string, int>(StringComparer.Ordinal);
    private readonly Dictionary<string, int> _debugCollectionPages = new Dictionary<string, int>(StringComparer.Ordinal);
    private readonly Dictionary<string, int> _debugMethodPages = new Dictionary<string, int>(StringComparer.Ordinal);
    private readonly Dictionary<string, List<DebugTypeEntry>> _debugTypeCategoryCache = new Dictionary<string, List<DebugTypeEntry>>(StringComparer.Ordinal);
    private readonly Dictionary<string, List<DebugMember>> _debugMemberCache = new Dictionary<string, List<DebugMember>>(StringComparer.Ordinal);
    private readonly Dictionary<string, List<MethodInfo>> _debugMethodCache = new Dictionary<string, List<MethodInfo>>(StringComparer.Ordinal);
    private readonly Dictionary<MethodInfo, string> _debugMethodSignatureCache = new Dictionary<MethodInfo, string>();
    private readonly Dictionary<string, DebugRawConfigCache> _debugRawConfigCache = new Dictionary<string, DebugRawConfigCache>(StringComparer.OrdinalIgnoreCase);
    private readonly Dictionary<string, DebugStringArrayFilterCache> _debugConfigFileFilterCache = new Dictionary<string, DebugStringArrayFilterCache>(StringComparer.Ordinal);
    private readonly Dictionary<string, DebugRawConfigEntryFilterCache> _debugRawConfigEntryFilterCache = new Dictionary<string, DebugRawConfigEntryFilterCache>(StringComparer.Ordinal);
    private readonly Dictionary<string, DebugBepInExPluginFilterCache> _debugBepInExPluginFilterCache = new Dictionary<string, DebugBepInExPluginFilterCache>(StringComparer.Ordinal);
    private readonly Dictionary<string, DebugTypeFilterCache> _debugTypeFilterCache = new Dictionary<string, DebugTypeFilterCache>(StringComparer.Ordinal);
    private readonly Dictionary<string, string> _pluginConfigValues = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
    private readonly Dictionary<string, bool> _pluginExpanded = new Dictionary<string, bool>(StringComparer.OrdinalIgnoreCase);
    private readonly Dictionary<string, bool> _pluginFunctionExpanded = new Dictionary<string, bool>(StringComparer.OrdinalIgnoreCase);
    private readonly Dictionary<string, EmpPluginDefinition> _pluginDefinitions = new Dictionary<string, EmpPluginDefinition>(StringComparer.OrdinalIgnoreCase);
    private readonly Dictionary<string, EmpFunctionState> _empFunctionStates = new Dictionary<string, EmpFunctionState>(StringComparer.OrdinalIgnoreCase);
    private string _pluginDefinitionsStamp = "";
    private bool _pluginDefinitionsDirty = true;
    private List<DebugTypeEntry> _debugGameTypeEntries;
    private string _debugCachedConfigFilesPath = "";
    private int _debugCachedConfigFilesFrame = -9999;
    private string[] _debugCachedConfigFiles = Array.Empty<string>();
    private int _debugCachedBepInExPluginsFrame = -9999;
    private List<DebugBepInExPlugin> _debugCachedBepInExPlugins = new List<DebugBepInExPlugin>();
}
