using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Net.Http;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.CompilerServices;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using BepInEx;
using BepInEx.Configuration;
using BepInEx.Logging;
using BepInEx.Unity.Bootstrap;
using HarmonyLib;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using UnityEngine;

public sealed partial class ElinModifierPlugin
{
    private bool _showAiApiKey;
    private bool _aiApiSettingsExpanded;
    private string _log = "";
    private string _itemLog = "";
    private string _npcLog = "";
    private string _playerInfoLog = "";
    private string _homeLog = "";
    private string _configLog = "";
    private string _nightlyFixSelfTalkBugConfigPassthroughJson = "";
    private string _aiLog = "";
    private string _aiApiBase = "https://api.openai.com/v1";
    private string _aiApiKey = "";
    private string _aiModelName = "";
    private string _aiPrompt = "";
    private string _aiResponse = "";
    private string _aiModelFilter = "";
    private string _aiLastRequestBody = "";
    private string _aiLastResponseBody = "";
    private bool _aiUseContext = true;
    private bool _aiAutoCompressContext = true;
    private bool _aiUseStreaming;
    private bool _aiUseToolStreaming;
    private string _aiHttpTimeoutSecondsText = AiHttpTimeoutDefaultSeconds.ToString(CultureInfo.InvariantCulture);
    private int _aiHttpTimeoutSeconds = AiHttpTimeoutDefaultSeconds;
    private bool _aiCompressionInProgress;
    private string _aiContextCompressThresholdText = AiContextCompressionDefaultThreshold.ToString(CultureInfo.InvariantCulture);
    private int _aiContextCompressThreshold = AiContextCompressionDefaultThreshold;
    private int _aiReasoningEffortIndex = 3;
    private bool _aiFetchModelsInProgress;
    private bool _aiSendInProgress;
    private int _aiRunId;
    private CancellationTokenSource _aiCancellation;
    private string _aiCurrentPrompt = "";
    private string _aiCurrentToolResults = "";
    private string _aiCurrentPartialResponse = "";
    private readonly List<AiPendingDangerousAction> _aiPendingDangerousActions = new List<AiPendingDangerousAction>();
    private int _aiDangerousActionSeq;
    private Harmony? _aiRuntimeHarmony;
    private readonly Dictionary<string, AiRuntimePatchRecord> _aiRuntimePatches = new Dictionary<string, AiRuntimePatchRecord>(StringComparer.Ordinal);
    private readonly Dictionary<string, object> _aiRuntimePatchReturnValues = new Dictionary<string, object>(StringComparer.Ordinal);
    private readonly Dictionary<string, Assembly> _aiRuntimeCompiledPatchAssemblies = new Dictionary<string, Assembly>(StringComparer.Ordinal);
    private readonly Dictionary<string, MethodInfo> _aiRuntimeCompiledPatchMethods = new Dictionary<string, MethodInfo>(StringComparer.Ordinal);
    private readonly Dictionary<string, AiRuntimeWorkspaceTextJob> _aiRuntimeWorkspaceJobs = new Dictionary<string, AiRuntimeWorkspaceTextJob>(StringComparer.Ordinal);
    private readonly object _aiRuntimeWorkspaceJobsLock = new object();
    private int _aiRuntimePatchSeq;
}
