using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Net.Http;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.CompilerServices;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Threading;
using System.Threading.Tasks;
using BepInEx;
using BepInEx.Configuration;
using BepInEx.Logging;
using BepInEx.Unity.Bootstrap;
using HarmonyLib;
using UnityEngine;

public sealed partial class ElinModifierPlugin
{
    private bool _playerInfoLoaded;
    private int _playerInfoLoadedUid;
    private string _playerInfoName = "";
    private string _playerInfoAlias = "";
    private string _playerInfoHonorific = "";
    private string _playerInfoRaceId = "";
    private string _playerInfoJobId = "";
    private string _playerInfoFaithId = "";
    private string _playerInfoFactionId = "";
    private string _playerInfoGender = "";
    private string _playerInfoAge = "";
    private string _playerInfoHeight = "";
    private string _playerInfoWeight = "";
    private string _playerInfoBirthYear = "";
    private string _playerInfoBirthMonth = "";
    private string _playerInfoBirthDay = "";
    private string _playerInfoHomeId = "";
    private string _playerInfoLocId = "";
    private string _playerInfoDadId = "";
    private string _playerInfoDadAdvId = "";
    private string _playerInfoMomId = "";
    private string _playerInfoMomAdvId = "";
    private string _playerInfoLikeCategoryId = "";
    private string _playerInfoLikeFoodId = "";
    private string _playerInfoDomains = "";
    private string _playerInfoHobbies = "";
    private string _playerInfoWorks = "";
    private string _playerInfoTotalFeat = "";
    private string _playerInfoNote = "";
    private string _playerInfoMemo = "";
    private string _playerInfoMemo2 = "";
    private string _playerInfoBackground = "";
}
