using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Net.Http;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.CompilerServices;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Threading;
using System.Threading.Tasks;
using BepInEx;
using BepInEx.Configuration;
using BepInEx.Logging;
using BepInEx.Unity.Bootstrap;
using HarmonyLib;
using UnityEngine;

public sealed partial class ElinModifierPlugin
{
    private string _itemDataEditorName = "";
    private string _itemDataEditorLv = "";
    private string _itemDataEditorEncLv = "";
    private string _itemDataEditorMaterialId = "";
    private string _itemDataEditorWeight = "";
    private string _itemDataEditorSkin = "";
    private string _itemDataEditorPriceFix = "";
    private string _itemDataEditorValue = "";
    private string _itemDataEditorValueBonus = "";
    private string _itemEnchantFilter = "";
    private string _foodEditorName = "";
    private string _foodEditorLv = "";
    private string _foodEditorEncLv = "";
    private string _foodEditorMaterialId = "";
    private string _foodEditorWeight = "";
    private string _foodEditorDecay = "";
    private string _foodEffectFilter = "";
    private string _weaponEnchantFilter = "";
    private string _itemDataEditorLoadedPriceFixText = "";
    private string _itemDataEditorLoadedValueText = "";
    private int _itemDataEditorLoadedPriceFixRaw;
    private int _itemDataEditorLoadedValueRaw;
    private int _itemDataEditorRarityValue;
    private int _itemDataEditorBlessedStateValue;
    private bool _itemDataEditorFlagStolen;
    private bool _itemDataEditorFlagCrafted;
    private bool _itemDataEditorFlagGifted;
    private bool _itemDataEditorFlagReplica;
    private bool _itemDataEditorFlagCopy;
    private bool _itemDataEditorFlagFireproof;
    private bool _itemDataEditorFlagAcidproof;
    private bool _itemDataEditorFlagBroken;
    private bool _itemDataEditorFlagNoSell;
    private bool _itemDataEditorFlagLostProperty;
    private Thing? _itemDataEditorTarget;
}
