using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Net.Http;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.CompilerServices;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Threading;
using System.Threading.Tasks;
using BepInEx;
using BepInEx.Configuration;
using BepInEx.Logging;
using BepInEx.Unity.Bootstrap;
using HarmonyLib;
using UnityEngine;

public sealed partial class ElinModifierPlugin
{
    private string _geneEditorName = "";
    private string _geneEditorSourceId = "";
    private string _geneEditorLv = "";
    private string _geneEditorSeed = "";
    private string _geneEditorCost = "";
    private string _geneEditorSlot = "";
    private string _geneSourceFilter = "";
    private string _geneEffectFilter = "";
    private int _npcGeneSelectedIndex = -1;
    private int _npcGeneLastTargetUid = -1;
    private int _etherDiseaseSelectedIndex = -1;
    private int _etherDiseaseLastTargetUid = -1;
    private int _npcGeneTypeIndex = 1;
    private bool _npcGeneIsManiGene;
    private string _npcGeneSourceId = "";
    private string _npcGeneLv = "";
    private string _npcGeneSeed = "";
    private string _npcGeneCost = "";
    private string _npcGeneSlot = "";
    private string _npcGeneSourceFilter = "";
    private string _npcGeneEffectFilter = "";
    private string _etherDiseaseId = "";
    private string _etherDiseaseValue = "";
    private string _etherDiseaseFilter = "";
    private string _lastEtherDiseaseFilter = "";
    private string _lastItemEnchantFilter = "";
    private string _lastFoodEffectFilter = "";
    private string _lastWeaponEnchantFilter = "";
    private Thing? _geneEditorTarget;
    private readonly List<GeneValueInput> _itemDataEditorEnchantments = new List<GeneValueInput>();
    private readonly HashSet<int> _itemDataEditorLoadedEnchantIds = new HashSet<int>();
    private readonly List<GeneValueInput> _foodEditorEffects = new List<GeneValueInput>();
    private readonly HashSet<int> _foodEditorLoadedEffectIds = new HashSet<int>();
    private readonly List<GeneValueInput> _weaponEditorEnchantments = new List<GeneValueInput>();
    private readonly HashSet<int> _weaponEditorLoadedEnchantIds = new HashSet<int>();
    private readonly List<GeneValueInput> _geneEditorValues = new List<GeneValueInput>();
    private readonly List<GeneValueInput> _npcGeneEditorValues = new List<GeneValueInput>();
}
