using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Net.Http;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.CompilerServices;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using BepInEx;
using BepInEx.Configuration;
using BepInEx.Logging;
using BepInEx.Unity.Bootstrap;
using HarmonyLib;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using UnityEngine;

public sealed partial class ElinModifierPlugin
{
    private const string DefaultNpcMoreInfoLevelColor = "#28FF28";
    private const string DefaultNpcMoreInfoIdentityColor = "#FFFFFF";
    private const string DefaultNpcMoreInfoRelationColor = "#FFFFFF";
    private const string DefaultNpcMoreInfoHpColor = "#FF0000";
    private const string DefaultNpcMoreInfoMpColor = "#0080FF";
    private const string DefaultNpcMoreInfoSpColor = "#F9F900";
    private const string DefaultNpcMoreInfoExpColor = "#00FF00";
    private const string DefaultNpcMoreInfoSpeedColor = "#FFFFFF";
    private const string DefaultNpcMoreInfoDvColor = "#FFFFFF";
    private const string DefaultNpcMoreInfoPvColor = "#FFFFFF";
    private const string DefaultNpcMoreInfoSkillColor = "#33CCFF";
    private const string DefaultNpcMoreInfoAbilityColor = "#66FFFF";
    private const string DefaultNpcMoreInfoFeatColor = "#00FFCC";
    private const string DefaultNpcMoreInfoCombatColor = "#FFFF00";
    private const string DefaultNpcMoreInfoResistColor = "#99FF00";
    private const string DefaultNpcMoreInfoAttributeColor = "#CCFF33";
    private const string DefaultNpcMoreInfoBuffColor = "#FF80FF";
    private const string DefaultItemMoreInfoBasicInfoColor = "#FFFF00";
    private const string DefaultItemMoreInfoGatheringToolColor = "#00BFFF";
    private const string DefaultItemMoreInfoGatheringThresholdColor = "#FFFF00";
    private const string DefaultItemMoreInfoGatheringValueColor = "#FFFFFF";
    private const string DefaultItemMoreInfoWeaponStatsColor = "#66CCFF";
    private const string DefaultItemMoreInfoEnchantColor = "#00FF00";
    private const string DefaultItemMoreInfoPlantStatsColor = "#66FF99";
    private const string DefaultItemMoreInfoRarityCrudeColor = "#FFFFFF";
    private const string DefaultItemMoreInfoRarityNormalColor = "#00FF00";
    private const string DefaultItemMoreInfoRaritySuperiorColor = "#00FFFF";
    private const string DefaultItemMoreInfoRarityLegendaryColor = "#FF00FF";
    private const string DefaultItemMoreInfoRarityMythicalColor = "#FFA500";
    private const string DefaultItemMoreInfoRarityArtifactColor = "#FF0000";
    internal static string NpcMoreInfoLevelColor => Instance?._npcMoreInfoLevelColor ?? DefaultNpcMoreInfoLevelColor;
    internal static string NpcMoreInfoIdentityColor => Instance?._npcMoreInfoIdentityColor ?? DefaultNpcMoreInfoIdentityColor;
    internal static string NpcMoreInfoRelationColor => Instance?._npcMoreInfoRelationColor ?? DefaultNpcMoreInfoRelationColor;
    internal static string NpcMoreInfoHpColor => Instance?._npcMoreInfoHpColor ?? DefaultNpcMoreInfoHpColor;
    internal static string NpcMoreInfoMpColor => Instance?._npcMoreInfoMpColor ?? DefaultNpcMoreInfoMpColor;
    internal static string NpcMoreInfoSpColor => Instance?._npcMoreInfoSpColor ?? DefaultNpcMoreInfoSpColor;
    internal static string NpcMoreInfoExpColor => Instance?._npcMoreInfoExpColor ?? DefaultNpcMoreInfoExpColor;
    internal static string NpcMoreInfoSpeedColor => Instance?._npcMoreInfoSpeedColor ?? DefaultNpcMoreInfoSpeedColor;
    internal static string NpcMoreInfoDvColor => Instance?._npcMoreInfoDvColor ?? DefaultNpcMoreInfoDvColor;
    internal static string NpcMoreInfoPvColor => Instance?._npcMoreInfoPvColor ?? DefaultNpcMoreInfoPvColor;
    internal static string NpcMoreInfoSkillColor => Instance?._npcMoreInfoSkillColor ?? DefaultNpcMoreInfoSkillColor;
    internal static string NpcMoreInfoAbilityColor => Instance?._npcMoreInfoAbilityColor ?? DefaultNpcMoreInfoAbilityColor;
    internal static string NpcMoreInfoFeatColor => Instance?._npcMoreInfoFeatColor ?? DefaultNpcMoreInfoFeatColor;
    internal static string NpcMoreInfoCombatColor => Instance?._npcMoreInfoCombatColor ?? DefaultNpcMoreInfoCombatColor;
    internal static string NpcMoreInfoResistColor => Instance?._npcMoreInfoResistColor ?? DefaultNpcMoreInfoResistColor;
    internal static string NpcMoreInfoAttributeColor => Instance?._npcMoreInfoAttributeColor ?? DefaultNpcMoreInfoAttributeColor;
    internal static string NpcMoreInfoBuffColor => Instance?._npcMoreInfoBuffColor ?? DefaultNpcMoreInfoBuffColor;
    internal static string ItemMoreInfoBasicInfoColor => Instance?._itemMoreInfoBasicInfoColor ?? DefaultItemMoreInfoBasicInfoColor;
    internal static string ItemMoreInfoGatheringToolColor => Instance?._itemMoreInfoGatheringToolColor ?? DefaultItemMoreInfoGatheringToolColor;
    internal static string ItemMoreInfoGatheringThresholdColor => Instance?._itemMoreInfoGatheringThresholdColor ?? DefaultItemMoreInfoGatheringThresholdColor;
    internal static string ItemMoreInfoGatheringValueColor => DefaultItemMoreInfoGatheringValueColor;
    internal static string ItemMoreInfoWeaponStatsColor => Instance?._itemMoreInfoWeaponStatsColor ?? DefaultItemMoreInfoWeaponStatsColor;
    internal static string ItemMoreInfoEnchantColor => Instance?._itemMoreInfoEnchantColor ?? DefaultItemMoreInfoEnchantColor;
    internal static string ItemMoreInfoPlantStatsColor => Instance?._itemMoreInfoPlantStatsColor ?? DefaultItemMoreInfoPlantStatsColor;
    internal static string ItemMoreInfoRarityCrudeColor => Instance?._itemMoreInfoRarityCrudeColor ?? DefaultItemMoreInfoRarityCrudeColor;
    internal static string ItemMoreInfoRarityNormalColor => Instance?._itemMoreInfoRarityNormalColor ?? DefaultItemMoreInfoRarityNormalColor;
    internal static string ItemMoreInfoRaritySuperiorColor => Instance?._itemMoreInfoRaritySuperiorColor ?? DefaultItemMoreInfoRaritySuperiorColor;
    internal static string ItemMoreInfoRarityLegendaryColor => Instance?._itemMoreInfoRarityLegendaryColor ?? DefaultItemMoreInfoRarityLegendaryColor;
    internal static string ItemMoreInfoRarityMythicalColor => Instance?._itemMoreInfoRarityMythicalColor ?? DefaultItemMoreInfoRarityMythicalColor;
    internal static string ItemMoreInfoRarityArtifactColor => Instance?._itemMoreInfoRarityArtifactColor ?? DefaultItemMoreInfoRarityArtifactColor;
    private static WidgetMouseover? _npcMoreInfoHoverWidget;
    private static RectTransform? _npcMoreInfoHoverRootRect;
    private static RectTransform? _npcMoreInfoHoverLayoutRect;
    private static Vector2 _npcMoreInfoHoverOriginalRootPivot;
    private static Vector2 _npcMoreInfoHoverOriginalLayoutPivot;
    private static int _npcMoreInfoExpectedHoverFrame = -1;
    private static string _npcMoreInfoExpectedHoverBlock = "";
    internal static readonly int[] NpcMoreInfoAttributeIds = { 70, 71, 72, 73, 74, 75, 76, 77 };
    internal static readonly int[] NpcMoreInfoCombatFingerprintElementIds = { 92, 100, 101, 102, 103, 130, 1355, 1421 };
    internal static readonly string[] NpcMoreInfoAttributeLabelsZh = { "力量", "体质", "灵巧", "感知", "学习", "意志", "魔力", "魅力" };
    internal static readonly string[] NpcMoreInfoAttributeLabelsEn = { "STR", "END", "DEX", "PER", "LER", "WIL", "MAG", "CHA" };
}
